// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TimeClient is the client API for Time service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimeClient interface {
	LocalTime(ctx context.Context, in *LocalTimeRequest, opts ...grpc.CallOption) (*LocalTimeResponse, error)
	RemoteTime(ctx context.Context, in *RemoteTimeRequest, opts ...grpc.CallOption) (*RemoteTimeResponse, error)
}

type timeClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeClient(cc grpc.ClientConnInterface) TimeClient {
	return &timeClient{cc}
}

func (c *timeClient) LocalTime(ctx context.Context, in *LocalTimeRequest, opts ...grpc.CallOption) (*LocalTimeResponse, error) {
	out := new(LocalTimeResponse)
	err := c.cc.Invoke(ctx, "/Time/LocalTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeClient) RemoteTime(ctx context.Context, in *RemoteTimeRequest, opts ...grpc.CallOption) (*RemoteTimeResponse, error) {
	out := new(RemoteTimeResponse)
	err := c.cc.Invoke(ctx, "/Time/RemoteTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeServer is the server API for Time service.
// All implementations must embed UnimplementedTimeServer
// for forward compatibility
type TimeServer interface {
	LocalTime(context.Context, *LocalTimeRequest) (*LocalTimeResponse, error)
	RemoteTime(context.Context, *RemoteTimeRequest) (*RemoteTimeResponse, error)
	mustEmbedUnimplementedTimeServer()
}

// UnimplementedTimeServer must be embedded to have forward compatible implementations.
type UnimplementedTimeServer struct {
}

func (UnimplementedTimeServer) LocalTime(context.Context, *LocalTimeRequest) (*LocalTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocalTime not implemented")
}
func (UnimplementedTimeServer) RemoteTime(context.Context, *RemoteTimeRequest) (*RemoteTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoteTime not implemented")
}
func (UnimplementedTimeServer) mustEmbedUnimplementedTimeServer() {}

// UnsafeTimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeServer will
// result in compilation errors.
type UnsafeTimeServer interface {
	mustEmbedUnimplementedTimeServer()
}

func RegisterTimeServer(s grpc.ServiceRegistrar, srv TimeServer) {
	s.RegisterService(&Time_ServiceDesc, srv)
}

func _Time_LocalTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServer).LocalTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Time/LocalTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServer).LocalTime(ctx, req.(*LocalTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Time_RemoteTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServer).RemoteTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Time/RemoteTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServer).RemoteTime(ctx, req.(*RemoteTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Time_ServiceDesc is the grpc.ServiceDesc for Time service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Time_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Time",
	HandlerType: (*TimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LocalTime",
			Handler:    _Time_LocalTime_Handler,
		},
		{
			MethodName: "RemoteTime",
			Handler:    _Time_RemoteTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "time.proto",
}
